baseURL = "https://boakye.yiadom.org/"
languageCode = "en-us"
title = "Insignificant Truths"
theme = "hugo-zen"
copyright = "2018 Yaw Boakye"
pygmentsStyle = "trac"

[author]
name = "Yaw Boakye"

[params]
twitter = "https://twitter.com/ejnbo"
github = "https://github.com/yawboakye"

[markup.goldmark.renderer]
unsafe= true
